// ─── Default Rule Set ──────────────────────────────────────
export const DEFAULT_RULES = {
  version: 1,
  scoring: {
    roi_weight: 0.25,
    consistency_weight: 0.25,
    copyability_weight: 0.20,
    category_edge_weight: 0.15,
    liquidity_quality_weight: 0.10,
    entry_timing_weight: 0.05,
    one_hit_wonder_threshold: 0.60,
    one_hit_wonder_penalty: 0.40,
    min_resolved_trades: 5,
    max_average_spread: 0.05,
    max_price_move_after_entry: 0.10,
    min_liquidity: 500,
    track_threshold: 0.70,
    watch_threshold: 0.40,
    ignore_threshold: 0.0,
  },
  trade_scoring: {
    wallet_global_weight: 0.15,
    wallet_category_weight: 0.10,
    price_movement_weight: 0.10,
    spread_weight: 0.15,
    liquidity_weight: 0.15,
    time_to_resolution_weight: 0.10,
    thesis_weight: 0.10,
    entry_timing_weight: 0.15,
    paper_copy_threshold: 0.65,
    watchlist_threshold: 0.40,
    skip_threshold: 0.0,
    max_spread: 0.08,
    min_liquidity: 300,
    max_price_moved: 0.15,
    max_time_since_entry_ms: 3600000,
  },
  paper_trading: {
    min_position_size: 5,
    max_position_size: 20,
    default_position_size: 10,
    confidence_size_multiplier: true,
  },
  improvement: {
    auto_update_enabled: true,
    min_evidence_trades: 10,
    max_changes_per_day: 3,
    learning_rate: 0.05,
  },
} as const;
