/**
 * Automated Polymarket Leaderboard Scraper
 * Uses Playwright to scrape polymarket.com/leaderboard
 * Extracts top traders with all-time profit and volume.
 * Updates src/lib/adapters/leaderboard-scraper.ts with fresh data.
 *
 * Usage: npx tsx src/cli/scrape-leaderboard.ts
 */

import { chromium } from "playwright";
import * as fs from "fs";
import * as path from "path";

interface ScrapedTrader {
  username: string;
  profit: number;
  volume: number;
}

async function scrapeLeaderboard(): Promise<ScrapedTrader[]> {
  console.log("[scraper] Launching headless browser...");
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();

  try {
    // Navigate to leaderboard - use domcontentloaded since PM is a heavy SPA
    console.log("[scraper] Navigating to polymarket.com/leaderboard...");
    await page.goto("https://polymarket.com/leaderboard", {
      waitUntil: "domcontentloaded",
      timeout: 60000,
    });

    // Wait for the leaderboard list to render (may take a few seconds for JS to load)
    await page.waitForSelector("main li", { timeout: 30000 });
    // Extra wait for dynamic content to populate
    await page.waitForTimeout(3000);
    console.log("[scraper] Leaderboard loaded.");

    // Click "All" time filter for all-time data
    const allButton = page.locator('button', { hasText: 'All' });
    if (await allButton.count() > 0) {
      await allButton.first().click();
      await page.waitForTimeout(2000); // wait for re-render
      console.log("[scraper] Switched to All-time view.");
    }

    // Also ensure we're sorted by Profit/Loss (not Volume)
    const profitButton = page.locator('button', { hasText: 'Profit/Loss' });
    if (await profitButton.count() > 0) {
      await profitButton.first().click();
      await page.waitForTimeout(1500);
    }

    // Extract trader data
    const traders = await page.evaluate(() => {
      const rows = document.querySelectorAll("main li");
      const result: Array<{ username: string; profit: number; volume: number }> = [];

      rows.forEach((li) => {
        const ps = li.querySelectorAll("p");
        if (ps.length >= 3) {
          const username = ps[0]?.textContent?.trim() || "";
          const pnlText = ps[1]?.textContent?.trim() || "$0";
          const volText = ps[2]?.textContent?.trim() || "$0";

          const profit = parseFloat(pnlText.replace(/[+$,\s]/g, "")) || 0;
          const volume = parseFloat(volText.replace(/[+$,\s]/g, "")) || 0;

          if (username && (profit > 0 || volume > 0)) {
            result.push({ username, profit, volume });
          }
        }
      });

      return result;
    });

    console.log(`[scraper] Extracted ${traders.length} traders.`);
    return traders;
  } finally {
    await browser.close();
  }
}

function updateScraperFile(traders: ScrapedTrader[]): void {
  const filePath = path.join(
    process.cwd(),
    "src",
    "lib",
    "adapters",
    "leaderboard-scraper.ts"
  );

  const tradersJson = traders
    .map((t) => `  { username: "${t.username}", profit: ${t.profit}, volume: ${t.volume} }`)
    .join(",\n");

  const content = `// ─── Polymarket Leaderboard Scraper ─────────────────────────
// Auto-generated by scrape-leaderboard.ts
// Last updated: ${new Date().toISOString()}
// Real trader data scraped from polymarket.com/leaderboard

export interface ScrapedTrader {
  username: string;
  profit: number;  // all-time profit in USD
  volume: number;  // all-time volume in USD
}

export const LEADERBOARD_DATA: ScrapedTrader[] = [
${tradersJson},
];

/**
 * Convert scraped traders to wallet profiles compatible with compute pipeline.
 */
export function scrapedToWallets(traders: ScrapedTrader[]): Array<{
  address: string;
  label: string;
  roi30d: number;
  winRate30d: number;
  tradeCount30d: number;
  resolvedTradeCount30d: number;
  bestCategory: string;
  averageTradeSize: number;
  averageLiquidity: number;
  averageSpread: number;
  averageEntryTiming: number;
  volume: number;
  consistencyScore: number;
  copyabilityScore: number;
}> {
  const categories = ["Politics", "Crypto", "Sports", "Economics", "Science", "Pop Culture"];

  return traders.map((t, i) => {
    const estimatedRoi = t.volume > 0 ? Math.min(t.profit / t.volume, 2.0) : 0.3;
    const winRate = estimatedRoi > 0.5 ? 0.6 + Math.random() * 0.2 :
      estimatedRoi > 0.2 ? 0.5 + Math.random() * 0.15 :
      0.4 + Math.random() * 0.15;
    const tradeCount = Math.max(10, Math.floor(t.volume / 5000));
    const resolvedCount = Math.floor(tradeCount * (0.4 + Math.random() * 0.4));
    const avgSpread = Math.max(0.01, 0.05 - estimatedRoi * 0.03 + (Math.random() - 0.5) * 0.02);
    const avgLiquidity = t.volume > 1000000 ? 5000 + Math.random() * 10000 :
      1000 + Math.random() * 5000;
    const consistencyBase = Math.min(1, tradeCount / 100) * 0.5 + winRate * 0.5;
    const consistency = Math.round(consistencyBase * 1000) / 1000;
    const copyBase = Math.min(1,
      estimatedRoi * 0.4 + (1 - avgSpread) * 0.3 + Math.min(t.volume / 500000, 1) * 0.3
    );
    const copyability = Math.round(copyBase * 1000) / 1000;

    return {
      address: \`0xPM_\${t.username.substring(0, 8)}\`,
      label: t.username,
      roi30d: Math.round(estimatedRoi * 1000) / 1000,
      winRate30d: Math.round(winRate * 1000) / 1000,
      tradeCount30d: tradeCount,
      resolvedTradeCount30d: resolvedCount,
      bestCategory: categories[i % categories.length],
      averageTradeSize: Math.round((t.volume / Math.max(tradeCount, 1)) * 100) / 100,
      averageLiquidity: Math.round(avgLiquidity),
      averageSpread: Math.round(avgSpread * 10000) / 10000,
      averageEntryTiming: Math.round((0.1 + Math.random() * 0.5) * 1000) / 1000,
      volume: t.volume,
      consistencyScore: consistency,
      copyabilityScore: copyability,
    };
  });
}
`;

  fs.writeFileSync(filePath, content, "utf-8");
  console.log(`[scraper] Updated ${filePath} with ${traders.length} traders.`);
}

async function main() {
  try {
    const traders = await scrapeLeaderboard();

    if (traders.length === 0) {
      console.error("[scraper] No traders extracted. Aborting update.");
      process.exit(1);
    }

    updateScraperFile(traders);

    console.log("[scraper] ✅ Leaderboard data updated successfully!");
    console.log(`[scraper] Top trader: ${traders[0].username} — $${traders[0].profit.toLocaleString()}`);
  } catch (e) {
    console.error("[scraper] Failed:", e instanceof Error ? e.message : e);
    process.exit(1);
  }
}

main();
