// ─── Polymarket Leaderboard Scraper ─────────────────────────
// Auto-generated by scrape-leaderboard.ts
// Last updated: 2026-07-07T04:17:16.110Z
// Real trader data scraped from polymarket.com/leaderboard

export interface ScrapedTrader {
  username: string;
  profit: number;  // all-time profit in USD
  volume: number;  // all-time volume in USD
}

export const LEADERBOARD_DATA: ScrapedTrader[] = [
  { username: "Theo4", profit: 22053934, volume: 43013259 },
  { username: "swisstony", profit: 16787692, volume: 1514916302 },
  { username: "Fredi9999", profit: 16619507, volume: 76611317 },
  { username: "kch123", profit: 11386691, volume: 293707579 },
  { username: "RN1", profit: 10812304, volume: 846590595 },
  { username: "mintblade", profit: 9238345, volume: 17759922 },
  { username: "fishalive", profit: 9063378, volume: 13281460 },
  { username: "frostrizz", profit: 8928561, volume: 23091318 },
  { username: "Len9311238", profit: 8709973, volume: 16402745 },
  { username: "sparklingwater123", profit: 8474966, volume: 19001699 },
  { username: "zxgngl", profit: 7807266, volume: 40551791 },
  { username: "GRIMDRIP", profit: 7602742, volume: 13603969 },
  { username: "RepTrump", profit: 7532410, volume: 13983231 },
  { username: "endlessFate", profit: 7409837, volume: 26282165 },
  { username: "0x2c335066FE58fe9237c3d3Dc7b275C2a034a0563-1759935795465", profit: 6456871, volume: 610951034 },
  { username: "PrincessCaro", profit: 6083643, volume: 23520810 },
  { username: "walletmobile", profit: 5942685, volume: 32196692 },
  { username: "KeyTransporter", profit: 5711460, volume: 20086062 },
  { username: "BetTom42", profit: 5642136, volume: 11212840 },
  { username: "mikatrade77", profit: 5147999, volume: 10884765 },
];

/**
 * Convert scraped traders to wallet profiles compatible with compute pipeline.
 */
export function scrapedToWallets(traders: ScrapedTrader[]): Array<{
  address: string;
  label: string;
  roi30d: number;
  winRate30d: number;
  tradeCount30d: number;
  resolvedTradeCount30d: number;
  bestCategory: string;
  averageTradeSize: number;
  averageLiquidity: number;
  averageSpread: number;
  averageEntryTiming: number;
  volume: number;
  consistencyScore: number;
  copyabilityScore: number;
}> {
  const categories = ["Politics", "Crypto", "Sports", "Economics", "Science", "Pop Culture"];

  return traders.map((t, i) => {
    const estimatedRoi = t.volume > 0 ? Math.min(t.profit / t.volume, 2.0) : 0.3;
    const winRate = estimatedRoi > 0.5 ? 0.6 + Math.random() * 0.2 :
      estimatedRoi > 0.2 ? 0.5 + Math.random() * 0.15 :
      0.4 + Math.random() * 0.15;
    const tradeCount = Math.max(10, Math.floor(t.volume / 5000));
    const resolvedCount = Math.floor(tradeCount * (0.4 + Math.random() * 0.4));
    const avgSpread = Math.max(0.01, 0.05 - estimatedRoi * 0.03 + (Math.random() - 0.5) * 0.02);
    const avgLiquidity = t.volume > 1000000 ? 5000 + Math.random() * 10000 :
      1000 + Math.random() * 5000;
    const consistencyBase = Math.min(1, tradeCount / 100) * 0.5 + winRate * 0.5;
    const consistency = Math.round(consistencyBase * 1000) / 1000;
    const copyBase = Math.min(1,
      estimatedRoi * 0.4 + (1 - avgSpread) * 0.3 + Math.min(t.volume / 500000, 1) * 0.3
    );
    const copyability = Math.round(copyBase * 1000) / 1000;

    return {
      address: `0xPM_${t.username.substring(0, 8)}`,
      label: t.username,
      roi30d: Math.round(estimatedRoi * 1000) / 1000,
      winRate30d: Math.round(winRate * 1000) / 1000,
      tradeCount30d: tradeCount,
      resolvedTradeCount30d: resolvedCount,
      bestCategory: categories[i % categories.length],
      averageTradeSize: Math.round((t.volume / Math.max(tradeCount, 1)) * 100) / 100,
      averageLiquidity: Math.round(avgLiquidity),
      averageSpread: Math.round(avgSpread * 10000) / 10000,
      averageEntryTiming: Math.round((0.1 + Math.random() * 0.5) * 1000) / 1000,
      volume: t.volume,
      consistencyScore: consistency,
      copyabilityScore: copyability,
    };
  });
}
